name: Build and Deploy to GitHub Pages

# Khi nào workflow sẽ chạy
on:
  # Chạy khi có push vào branch main hoặc dev
  push:
    branches: [ main, dev ]
  
  # Chạy khi có pull request vào branch main hoặc dev  
  pull_request:
    branches: [ main, dev ]

  # Cho phép chạy manual từ Actions tab
  workflow_dispatch:

# Quyền cần thiết để deploy GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Chỉ cho phép 1 deployment chạy cùng lúc
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job để build dự án
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload thư mục dist sau khi build
        path: './dist'

  # Job để deploy lên GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
